spring.application.name=SpringEcom

spring.datasource.url = jdbc:postgresql://localhost:5432/SpringEcom

spring.datasource.username = postgres

spring.datasource.password = new_password

spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.auto-commit = false